// Code generated by Slice Machine. DO NOT EDIT.

import About from './About';
import Welcome from './Welcome';

export {
	About,
	Welcome,
};

export const components = {
	about: About,
	welcome: Welcome,
};
